# This is meant to be used with ./docker-compose.yml in production
services:
  storage:
    volumes:
      - ../../supabase/volumes/storage:/var/lib/storage

  db:
    volumes:
      # We keep the actual data in a volume outside of git, so it survives restarts
      - ../../supabase/volumes/db/data:/var/lib/postgresql/data
      # We pull in .sql migrations, schema files from the git repo
      - ./supabase/volumes/db/init:/docker-entrypoint-initdb.d

  pg_backup:
    environment:
      PG_HOST_PORT: 5432
    volumes:
      # Directory that will contain the database dumps
      - ../../supabase/volumes/backups/:/var/opt/pg_dumps/
      # Directory where all daily cron task scripts reside
      - ./supabase/backup/cron-tasks:/etc/periodic/daily:ro

  kong:
    volumes:
      - ../../config/kong.yml:/var/lib/kong/kong.yml
